# EDA

In [1]:
# Import Panda Library

import pandas as pd

In [2]:
# Python Package Installer

!pip install pandas

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [11]:
#importing the Dataset
df=pd.read_excel(r"C:\Users\Dell\Downloads\python_prac\Sales_Data_Cleaned.xlsx")

In [12]:
df

,Order ID,Order Date,Salesperson ID,Salesperson Name,Region,City,Product ID,Product Name,Category,Unit Price,Quantity,Discount,Revenue,Payment Mode,Order Status
0,ORD01215,2024-06-13,SP03,Ravi Kumar,East,Kolkata,PRD015,Dettol Liquid Soap 250ml,Personal Care,145,12.0,0.11,1548.60,Net Banking,Delivered
1,ORD01250,2024-09-13,SP012,Sneha Patil,West,Ahmedabad,PRD005,Bajaj Mixer Grinder 750W,Appliances,2100,17.0,0.06,33558.00,Debit Card,Pending
2,ORD01262,2024-09-17,SP05,Suresh Pillai,South,Hyderabad,PRD019,Classmate A4 Notebook 200pg,Stationery,85,20.0,0.03,1649.00,EMI,Delivered
3,ORD01301,2024-02-06,SP011,Nikhil Joshi,East,Kolkata,PRD008,American Tourister Trolley,Bags,4999,3.0,0.21,11847.63,Debit Card,Delivered
4,ORD01373,2024-05-21,SP011,Nikhil Joshi,East,Ranchi,PRD010,Bata Ladies Sandals,Footwear,1299,7.0,0.16,7638.12,Debit Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,ORD03348,2024-01-09,SP09,Manish Gupta,North,Jaipur,PRD009,Woodland Men Boots,Footwear,3499,18.0,0.24,47866.32,Cash,Pending
2396,ORD03355,2024-09-07,SP06,Anjali Mehta,North,Lucknow,PRD009,Woodland Men Boots,Footwear,3499,12.0,0.24,31910.88,EMI,Delivered
2397,ORD03363,2024-02-01,SP03,Ravi Kumar,East,Patna,PRD009,Woodland Men Boots,Footwear,3499,20.0,0.27,51085.40,Credit Card,Cancelled
2398,ORD03369,2024-10-17,SP011,Nikhil Joshi,East,Ranchi,PRD009,Woodland Men Boots,Footwear,3499,18.0,0.22,49125.96,Debit Card,Delivered
2399,ORD03383,2024-01-06,SP06,Anjali Mehta,North,Agra,PRD009,Woodland Men Boots,Footwear,3499,11.0,0.29,27327.19,Cash,Delivered

In [13]:
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\dell\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\dell\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [14]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine

# Connect MySQL
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Kamal@1224",
    database="sales_db"
)

print("✅ Successfully Connected!")

# SQLAlchemy Engine
engine = create_engine(
    "mysql+mysqlconnector://root:Kamal%401224@localhost/sales_db"
)

# Cursor
mycursor = mydb.cursor()

# Show tables
mycursor.execute("SHOW TABLES")

for table in mycursor:
    print(table)

✅ Successfully Connected!

In [15]:
table_name = "sales_db"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"✅ Data successfully loaded into table '{table_name}'")

✅ Data successfully loaded into table 'sales_db'

In [16]:
df.head(28)

,Order ID,Order Date,Salesperson ID,Salesperson Name,Region,City,Product ID,Product Name,Category,Unit Price,Quantity,Discount,Revenue,Payment Mode,Order Status
0,ORD01215,2024-06-13,SP03,Ravi Kumar,East,Kolkata,PRD015,Dettol Liquid Soap 250ml,Personal Care,145,12.0,0.11,1548.60,Net Banking,Delivered
1,ORD01250,2024-09-13,SP012,Sneha Patil,West,Ahmedabad,PRD005,Bajaj Mixer Grinder 750W,Appliances,2100,17.0,0.06,33558.00,Debit Card,Pending
2,ORD01262,2024-09-17,SP05,Suresh Pillai,South,Hyderabad,PRD019,Classmate A4 Notebook 200pg,Stationery,85,20.0,0.03,1649.00,EMI,Delivered
3,ORD01301,2024-02-06,SP011,Nikhil Joshi,East,Kolkata,PRD008,American Tourister Trolley,Bags,4999,3.0,0.21,11847.63,Debit Card,Delivered
4,ORD01373,2024-05-21,SP011,Nikhil Joshi,East,Ranchi,PRD010,Bata Ladies Sandals,Footwear,1299,7.0,0.16,7638.12,Debit Card,Delivered
5,ORD01411,2024-01-26,SP07,Rohit Verma,East,Ranchi,PRD009,Woodland Men Boots,Footwear,3499,6.0,0.01,20784.06,Credit Card,Delivered
6,ORD01523,2024-10-27,SP08,Kavitha Reddy,West,Ahmedabad,PRD005,Bajaj Mixer Grinder 750W,Appliances,2100,2.0,0.05,3990.00,EMI,Delivered
7,ORD01674,2024-03-23,SP04,Fatima Sheikh,West,Nagpur,PRD018,Maggi Noodles Pack of 12,Food & Bev,144,17.0,0.23,1884.96,EMI,Delivered
8,ORD01777,2024-11-27,SP05,Suresh Pillai,South,Coimbatore,PRD009,Woodland Men Boots,Footwear,3499,7.0,0.01,24248.07,Net Banking,Delivered
9,ORD01846,2024-09-28,SP010,Divya Iyer,South,Hyderabad,PRD017,Tata Gold Tea 500g,Food & Bev,299,8.0,0.23,1841.84,Cash,Delivered
10,ORD01850,2024-03-27,SP07,Rohit Verma,East,Guwahati,PRD015,Dettol Liquid Soap 250ml,Personal Care,145,10.0,0.05,1377.50,Debit Card,Returned
11,ORD01904,2024-11-23,SP07,Rohit Verma,East,Ranchi,PRD009,Woodland Men Boots,Footwear,3499,20.0,0.15,59483.00,Cash,Delivered
12,ORD02130,2024-12-02,SP05,Suresh Pillai,South,Bangalore,PRD019,Classmate A4 Notebook 200pg,Stationery,85,15.0,0.29,905.25,Debit Card,Delivered
13,ORD02187,2024-05-01,SP03,Ravi Kumar,East,Guwahati,PRD020,Cello Butterflow Pens Pk10,Stationery,75,6.0,0.00,450.00,Cash,Cancelled
14,ORD02249,2024-03-15,SP04,Fatima Sheikh,West,Pune,PRD015,Dettol Liquid Soap 250ml,Personal Care,145,8.0,0.10,1044.00,Debit Card,Delivered
15,ORD02292,2024-12-06,SP08,Kavitha Reddy,West,Pune,PRD011,Peter England Formal Shirt,Clothing,1199,6.0,0.28,5179.68,Net Banking,Delivered
16,ORD02296,2024-01-24,SP07,Rohit Verma,East,Kolkata,PRD017,Tata Gold Tea 500g,Food & Bev,299,15.0,0.08,4126.20,EMI,Delivered
17,ORD02430,2024-10-23,SP09,Manish Gupta,North,Delhi,PRD011,Peter England Formal Shirt,Clothing,1199,2.0,0.07,2230.14,Net Banking,Cancelled
18,ORD02441,2024-04-09,SP09,Manish Gupta,North,Lucknow,PRD010,Bata Ladies Sandals,Footwear,1299,8.0,0.16,8729.28,Net Banking,Delivered
19,ORD02458,2024-09-23,SP04,Fatima Sheikh,West,Mumbai,PRD002,iPhone 15 128GB,Electronics,79999,9.0,0.29,511193.61,Credit Card,Delivered
20,ORD02499,2024-01-18,SP011,Nikhil Joshi,East,Ranchi,PRD008,American Tourister Trolley,Bags,4999,1.0,0.09,4549.09,Debit Card,Delivered
21,ORD02512,2024-05-23,SP07,Rohit Verma,East,Guwahati,PRD010,Bata Ladies Sandals,Footwear,1299,14.0,0.03,17640.42,Debit Card,Delivered
22,ORD02521,2024-02-02,SP07,Rohit Verma,East,Kolkata,PRD005,Bajaj Mixer Grinder 750W,Appliances,2100,1.0,0.05,1995.00,Debit Card,Delivered
23,ORD02573,2024-11-24,SP06,Anjali Mehta,North,Agra,PRD010,Bata Ladies Sandals,Footwear,1299,14.0,0.18,14912.52,Debit Card,Delivered
24,ORD02658,2024-12-23,SP09,Manish Gupta,North,Chandigarh,PRD017,Tata Gold Tea 500g,Food & Bev,299,10.0,0.21,2362.10,Cash,Returned
25,ORD02682,2024-07-08,SP012,Sneha Patil,West,Mumbai,PRD006,Whirlpool 7kg Washing Machine,Appliances,22000,12.0,0.26,195360.00,Cash,Returned
26,ORD02701,2024-01-26,SP06,Anjali Mehta,North,Agra,PRD017,Tata Gold Tea 500g,Food & Bev,299,20.0,0.23,4604.60,Net Banking,Cancelled
27,ORD02711,2024-09-24,SP011,Nikhil Joshi,East,Guwahati,PRD020,Cello Butterflow Pens Pk10,Stationery,75,16.0,0.07,1116.00,Cash,Delivered